# Generated by Django 3.1 on 2024-06-17 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20240617_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='closebid',
            name='closed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='closebid',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
