# Generated by Django 3.1 on 2024-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20240617_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='closebid',
            name='paid_time',
            field=models.DateTimeField(null=True),
        ),
    ]
