# Generated by Django 3.1 on 2024-06-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_closebid_paid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='minimum_charge',
            field=models.IntegerField(default=19),
        ),
    ]
