# Generated by Django 3.1 on 2024-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20240619_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='isActive',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
