# Generated by Django 3.1 on 2024-06-19 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20240619_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.IntegerField()),
                ('username', models.TextField(max_length=500)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
