# Generated by Django 3.1 on 2024-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cause',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
