# Generated by Django 3.1 on 2024-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_transactions_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
